# monitoring/prometheus/prometheus.yml

global:
  scrape_interval: 15s # Default scrape interval

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'your-service'
    static_configs:
      - targets: ['your-service:8080'] # Replace with your actual service target

alerting:
  alertmanagers:
    - static_configs:
        - targets: ['alertmanager:9093']

rule_files:
  # - "alert_rules.yml" # Uncomment and configure your alerting rules here
