// ci-cd/pipelines/Jenkinsfile

pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                git 'https://github.com/humeshdeshmukh/Interview.ai'
            }
        }
        stage('Install Dependencies') {
            steps {
                sh 'npm install'
            }
        }
        stage('Run Tests') {
            steps {
                sh 'npm test'
            }
        }
        stage('Build') {
            steps {
                sh 'npm run build'
            }
        }
        stage('Deploy') {
            steps {
                sh './ci-cd/scripts/deploy.sh'
            }
        }
    }
    post {
        always {
            cleanWs()
        }
    }
}
