# monitoring/grafana/grafana.yml

# You can add any Grafana-specific configurations here
# This example uses a minimal configuration

apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
